[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm-8']

[phases.install]
cmds = ['cd .. && pnpm install --frozen-lockfile --filter=frontend...']

[phases.build]
cmds = ['cd .. && pnpm --filter=frontend run build']

[start]
cmd = 'cd .. && pnpm --filter=frontend start'
