[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
# Force pnpm and install from the root
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
# Build the specific package
cmds = ['pnpm run build --filter @workit/frontend']

[start]
# Start the specific package
cmd = 'pnpm run start --filter @workit/frontend'